name = 'camelot-sdk-armv7m-mainline'
license = 'Apache-2.0'
license_file = ['LICENSE.txt']
dts = 'dts/nucleo_u5a5.dts'
crossfile = 'arm-none-eabi-gcc.ini'
version = 'v0.1.0'

[kernel]
scm.git.uri = 'https://github.com/camelot-os/sentry-kernel.git'
scm.git.revision = 'v0.4.1'
build.options.with_doc = true
config = 'configs/sentry/sentry.config'

[runtime]
scm.git.uri = 'https://github.com/camelot-os/shield.git'
scm.git.revision = 'v0.1.0'
config = 'configs/shield/shield.config'

